spring.application.name=backend

# Datasource Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000

# JPA & Flyway
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

# Custom Application Properties
app.jwt.secret=${JWT_SECRET}
app.jwt.access-ttl=15m
app.refresh.ttl=7d
app.refresh.cookie-secure=${COOKIE_SECURE:false}
app.refresh.cookie-same-site=${COOKIE_SAMESITE:Strict}
app.cors.allowed-origin=${FRONTEND_ORIGIN:http://localhost:5173}


server.port=8082
